// src/components/bac/quiz/english.ts

import { Question, shuffleArray } from './types';

// دالة مساعدة لإنشاء أسئلة قواعد فريدة لكل مستوى
const generateGrammarQuestions = (levelNum: number): Question[] => {
  const allGrammarQuestions: Question[] = [
    // Transformations (Reported Speech, Passive, Too/Enough, So...that, etc.)
    { id: 'g-t-1', type: 'grammar-transform', questionText: "He said, 'I am happy.' (Reported Speech)", options: ["He said that he was happy.", "He said he is happy.", "He said he will be happy."], correct: "He said that he was happy." },
    { id: 'g-t-2', type: 'grammar-transform', questionText: "She asked, 'What is your name?' (Reported Question)", options: ["She asked what my name was.", "She asked what is your name.", "She asked what was my name."], correct: "She asked what my name was." },
    { id: 'g-t-3', type: 'grammar-transform', questionText: "They are building a new house. (Passive Voice)", options: ["A new house is being built by them.", "A new house was built by them.", "They built a new house."], correct: "A new house is being built by them." },
    { id: 'g-t-4', type: 'grammar-transform', questionText: "You must clean your room. (Passive Voice)", options: ["Your room must be cleaned.", "Your room is cleaned.", "Your room was cleaned."], correct: "Your room must be cleaned." },
    { id: 'g-t-5', type: 'grammar-transform', questionText: "He is too young to drive. (So...that)", options: ["He is so young that he cannot drive.", "He is so young that he can drive.", "He is too young that he cannot drive."], correct: "He is so young that he cannot drive." },
    { id: 'g-t-6', type: 'grammar-transform', questionText: "She is clever enough to solve it. (So...that)", options: ["She is so clever that she can solve it.", "She is so clever that she cannot solve it.", "She is clever that she can solve it."], correct: "She is so clever that she can solve it." },
    { id: 'g-t-7', type: 'grammar-transform', questionText: "I regret telling him. (I wish)", options: ["I wish I hadn't told him.", "I wish I didn't tell him.", "I wish I wouldn't tell him."], correct: "I wish I hadn't told him." },
    { id: 'g-t-8', type: 'grammar-transform', questionText: "It's high time you studied harder. (Rewrite)", options: ["You should study harder.", "You study harder now.", "You will study harder."], correct: "You should study harder." },
    { id: 'g-t-9', type: 'grammar-transform', questionText: "She bought a new car. (Turn into a question)", options: ["What did she buy?", "Did she buy a new car?", "She bought what?"], correct: "What did she buy?" },
    { id: 'g-t-10', type: 'grammar-transform', questionText: "They have finished their work. (Passive Voice)", options: ["Their work has been finished by them.", "Their work is finished by them.", "They finished their work."], correct: "Their work has been finished by them." },
    { id: 'g-t-11', type: 'grammar-transform', questionText: "He said, 'I will call you tomorrow.' (Reported Speech)", options: ["He said he would call me the next day.", "He said he will call me tomorrow.", "He said he called me."], correct: "He said he would call me the next day." },
    { id: 'g-t-12', type: 'grammar-transform', questionText: "The teacher told us, 'Don't make noise!' (Reported Command)", options: ["The teacher told us not to make noise.", "The teacher told us to not make noise.", "The teacher told us don't make noise."], correct: "The teacher told us not to make noise." },
    { id: 'g-t-13', type: 'grammar-transform', questionText: "Someone stole my wallet. (Passive Voice)", options: ["My wallet was stolen.", "My wallet is stolen.", "My wallet stolen."], correct: "My wallet was stolen." },
    { id: 'g-t-14', type: 'grammar-transform', questionText: "It's time for you to leave. (It's high time)", options: ["It's high time you left.", "It's high time you leave.", "It's high time you will leave."], correct: "It's high time you left." },
    { id: 'g-t-15', type: 'grammar-transform', questionText: "If I were a bird, I would fly. (Express regret)", options: ["I wish I were a bird.", "I regret not being a bird.", "I am not a bird."], correct: "I wish I were a bird." },
    { id: 'g-t-16', type: 'grammar-transform', questionText: "She said, 'I visited Paris last year.' (Reported Speech)", options: ["She said she had visited Paris the previous year.", "She said she visited Paris last year.", "She said she visits Paris."], correct: "She said she had visited Paris the previous year." },
    { id: 'g-t-17', type: 'grammar-transform', questionText: "He asked, 'Where do you live?' (Reported Question)", options: ["He asked where I lived.", "He asked where do you live.", "He asked where I live."], correct: "He asked where I lived." },
    { id: 'g-t-18', type: 'grammar-transform', questionText: "The dog bit the man. (Passive Voice)", options: ["The man was bitten by the dog.", "The man is bitten by the dog.", "The man bit the dog."], correct: "The man was bitten by the dog." },
    { id: 'g-t-19', type: 'grammar-transform', questionText: "It's too cold to go out. (So...that)", options: ["It's so cold that we cannot go out.", "It's so cold that we can go out.", "It's too cold that we cannot go out."], correct: "It's so cold that we cannot go out." },
    { id: 'g-t-20', type: 'grammar-transform', questionText: "I regret eating too much. (I wish)", options: ["I wish I hadn't eaten too much.", "I wish I didn't eat too much.", "I wish I wouldn't eat too much."], correct: "I wish I hadn't eaten too much." },
    { id: 'g-t-21', type: 'grammar-transform', questionText: "They will finish the project soon. (Passive Voice)", options: ["The project will be finished soon by them.", "The project is finished soon by them.", "The project has been finished soon by them."], correct: "The project will be finished soon by them." },
    { id: 'g-t-22', type: 'grammar-transform', questionText: "He said, 'I can swim.' (Reported Speech)", options: ["He said he could swim.", "He said he can swim.", "He said he would swim."], correct: "He said he could swim." },
    { id: 'g-t-23', type: 'grammar-transform', questionText: "She asked, 'Have you seen my keys?' (Reported Question)", options: ["She asked if I had seen her keys.", "She asked if I have seen her keys.", "She asked if I saw her keys."], correct: "She asked if I had seen her keys." },
    { id: 'g-t-24', type: 'grammar-transform', questionText: "We should help the poor. (Passive Voice)", options: ["The poor should be helped.", "The poor are helped.", "The poor were helped."], correct: "The poor should be helped." },
    { id: 'g-t-25', type: 'grammar-transform', questionText: "He is strong enough to lift it. (So...that)", options: ["He is so strong that he can lift it.", "He is so strong that he cannot lift it.", "He is strong that he can lift it."], correct: "He is so strong that he can lift it." },
    { id: 'g-t-26', type: 'grammar-transform', questionText: "I regret wasting my time. (I wish)", options: ["I wish I hadn't wasted my time.", "I wish I didn't waste my time.", "I wish I wouldn't waste my time."], correct: "I wish I hadn't wasted my time." },
    { id: 'g-t-27', type: 'grammar-transform', questionText: "It's high time he apologized. (Rewrite)", options: ["He should apologize.", "He apologizes now.", "He will apologize."], correct: "He should apologize." },
    { id: 'g-t-28', type: 'grammar-transform', questionText: "They invited me to the party. (Passive Voice)", options: ["I was invited to the party by them.", "I am invited to the party by them.", "I have been invited to the party by them."], correct: "I was invited to the party by them." },
    { id: 'g-t-29', type: 'grammar-transform', questionText: "She said, 'I like pizza.' (Reported Speech)", options: ["She said she liked pizza.", "She said she likes pizza.", "She said she will like pizza."], correct: "She said she liked pizza." },
    { id: 'g-t-30', type: 'grammar-transform', questionText: "He asked, 'When did you arrive?' (Reported Question)", options: ["He asked when I had arrived.", "He asked when did I arrive.", "He asked when I arrived."], correct: "He asked when I had arrived." },
    { id: 'g-t-31', type: 'grammar-transform', questionText: "They will deliver the package tomorrow. (Passive Voice)", options: ["The package will be delivered tomorrow.", "The package is delivered tomorrow.", "The package was delivered tomorrow."], correct: "The package will be delivered tomorrow." },
    { id: 'g-t-32', type: 'grammar-transform', questionText: "He is too busy to help. (So...that)", options: ["He is so busy that he cannot help.", "He is so busy that he can help.", "He is too busy that he cannot help."], correct: "He is so busy that he cannot help." },
    { id: 'g-t-33', type: 'grammar-transform', questionText: "I regret buying that car. (I wish)", options: ["I wish I hadn't bought that car.", "I wish I didn't buy that car.", "I wish I wouldn't buy that car."], correct: "I wish I hadn't bought that car." },
    { id: 'g-t-34', type: 'grammar-transform', questionText: "It's high time they learned the truth. (Rewrite)", options: ["They should learn the truth.", "They learn the truth now.", "They will learn the truth."], correct: "They should learn the truth." },
    { id: 'g-t-35', type: 'grammar-transform', questionText: "Someone has broken the window. (Passive Voice)", options: ["The window has been broken.", "The window was broken.", "The window is broken."], correct: "The window has been broken." },
    { id: 'g-t-36', type: 'grammar-transform', questionText: "She said, 'I have finished.' (Reported Speech)", options: ["She said she had finished.", "She said she has finished.", "She said she finished."], correct: "She said she had finished." },
    { id: 'g-t-37', type: 'grammar-transform', questionText: "He asked, 'Is it raining?' (Reported Question)", options: ["He asked if it was raining.", "He asked if it is raining.", "He asked if it rained."], correct: "He asked if it was raining." },
    { id: 'g-t-38', type: 'grammar-transform', questionText: "They painted the wall green. (Passive Voice)", options: ["The wall was painted green by them.", "The wall is painted green by them.", "The wall has been painted green by them."], correct: "The wall was painted green by them." },
    { id: 'g-t-39', type: 'grammar-transform', questionText: "He is old enough to vote. (So...that)", options: ["He is so old that he can vote.", "He is so old that he cannot vote.", "He is old that he can vote."], correct: "He is so old that he can vote." },
    { id: 'g-t-40', type: 'grammar-transform', questionText: "I regret not studying harder. (I wish)", options: ["I wish I had studied harder.", "I wish I studied harder.", "I wish I would study harder."], correct: "I wish I had studied harder." },
    { id: 'g-t-41', type: 'grammar-transform', questionText: "It's high time we left. (Rewrite)", options: ["We should leave.", "We leave now.", "We will leave."], correct: "We should leave." },
    { id: 'g-t-42', type: 'grammar-transform', questionText: "The police caught the thief. (Passive Voice)", options: ["The thief was caught by the police.", "The thief is caught by the police.", "The thief has been caught by the police."], correct: "The thief was caught by the police." },
    { id: 'g-t-43', type: 'grammar-transform', questionText: "She said, 'I bought a dress.' (Reported Speech)", options: ["She said she had bought a dress.", "She said she bought a dress.", "She said she buys a dress."], correct: "She said she had bought a dress." },
    { id: 'g-t-44', type: 'grammar-transform', questionText: "He asked, 'What are you doing?' (Reported Question)", options: ["He asked what I was doing.", "He asked what are you doing.", "He asked what I am doing."], correct: "He asked what I was doing." },
    { id: 'g-t-45', type: 'grammar-transform', questionText: "They will clean the office. (Passive Voice)", options: ["The office will be cleaned by them.", "The office is cleaned by them.", "The office was cleaned by them."], correct: "The office will be cleaned by them." },
    { id: 'g-t-46', type: 'grammar-transform', questionText: "He is rich enough to buy it. (So...that)", options: ["He is so rich that he can buy it.", "He is so rich that he cannot buy it.", "He is rich that he can buy it."], correct: "He is so rich that he can buy it." },
    { id: 'g-t-47', type: 'grammar-transform', questionText: "I regret shouting at her. (I wish)", options: ["I wish I hadn't shouted at her.", "I wish I didn't shout at her.", "I wish I wouldn't shout at her."], correct: "I wish I hadn't shouted at her." },
    { id: 'g-t-48', type: 'grammar-transform', questionText: "It's high time we started. (Rewrite)", options: ["We should start.", "We start now.", "We will start."], correct: "We should start." },
    { id: 'g-t-49', type: 'grammar-transform', questionText: "They have sold the car. (Passive Voice)", options: ["The car has been sold.", "The car was sold.", "The car is sold."], correct: "The car has been sold." },
    { id: 'g-t-50', type: 'grammar-transform', questionText: "She said, 'I love my job.' (Reported Speech)", options: ["She said she loved her job.", "She said she loves her job.", "She said she will love her job."], correct: "She said she loved her job." },

    // MCQs (Conditional, Wish, Providing that, As long as, It's high time)
    { id: 'g-mcq-1', type: 'grammar-mcq', questionText: "If I had studied, I ____ the exam. (pass)", options: ["will pass", "would pass", "would have passed"], correct: "would have passed" },
    { id: 'g-mcq-2', type: 'grammar-mcq', questionText: "I wish I ____ fly.", options: ["can", "could", "will"], correct: "could" },
    { id: 'g-mcq-3', type: 'grammar-mcq', questionText: "You can go out ____ you finish your homework.", options: ["unless", "providing that", "so that"], correct: "providing that" },
    { id: 'g-mcq-4', type: 'grammar-mcq', questionText: "As long as you ____ hard, you will succeed.", options: ["work", "worked", "working"], correct: "work" },
    { id: 'g-mcq-5', type: 'grammar-mcq', questionText: "It's high time you ____ harder. (study)", options: ["study", "studied", "will study"], correct: "studied" },
    { id: 'g-mcq-6', type: 'grammar-mcq', questionText: "If it ____ tomorrow, we will stay home. (rain)", options: ["rains", "rained", "had rained"], correct: "rains" },
    { id: 'g-mcq-7', type: 'grammar-mcq', questionText: "I wish I ____ taller.", options: ["am", "were", "was"], correct: "were" },
    { id: 'g-mcq-8', type: 'grammar-mcq', questionText: "We will go to the beach ____ the weather is good.", options: ["unless", "as long as", "despite"], correct: "as long as" },
    { id: 'g-mcq-9', type: 'grammar-mcq', questionText: "Providing that you ____ the rules, you can join.", options: ["follow", "followed", "will follow"], correct: "follow" },
    { id: 'g-mcq-10', type: 'grammar-mcq', questionText: "It's high time we ____. (leave)", options: ["leave", "left", "are leaving"], correct: "left" },
    { id: 'g-mcq-11', type: 'grammar-mcq', questionText: "If I ____ enough money, I would buy a car. (have)", options: ["have", "had", "will have"], correct: "had" },
    { id: 'g-mcq-12', type: 'grammar-mcq', questionText: "I wish I ____ speak French fluently.", options: ["can", "could", "will"], correct: "could" },
    { id: 'g-mcq-13', type: 'grammar-mcq', questionText: "You can borrow my book ____ you promise to return it.", options: ["unless", "providing that", "in case"], correct: "providing that" },
    { id: 'g-mcq-14', type: 'grammar-mcq', questionText: "As long as he ____ the truth, I will forgive him. (tell)", options: ["tells", "told", "telling"], correct: "tells" },
    { id: 'g-mcq-15', type: 'grammar-mcq', questionText: "It's high time the government ____ action. (take)", options: ["took", "take", "takes"], correct: "took" },
    { id: 'g-mcq-16', type: 'grammar-mcq', questionText: "If she ____ earlier, she wouldn't have missed the train. (leave)", options: ["left", "had left", "leaves"], correct: "had left" },
    { id: 'g-mcq-17', type: 'grammar-mcq', questionText: "I wish I ____ on vacation now.", options: ["am", "were", "was"], correct: "were" },
    { id: 'g-mcq-18', type: 'grammar-mcq', questionText: "You can achieve your goals ____ you work hard.", options: ["unless", "as long as", "even if"], correct: "as long as" },
    { id: 'g-mcq-19', type: 'grammar-mcq', questionText: "Providing that the weather ____ good, we'll go for a picnic.", options: ["is", "was", "will be"], correct: "is" },
    { id: 'g-mcq-20', type: 'grammar-mcq', questionText: "It's high time they ____ about their future. (think)", options: ["thought", "think", "are thinking"], correct: "thought" },
    { id: 'g-mcq-21', type: 'grammar-mcq', questionText: "If I ____ rich, I would travel the world. (be)", options: ["am", "were", "was"], correct: "were" },
    { id: 'g-mcq-22', type: 'grammar-mcq', questionText: "I wish I ____ more time to read.", options: ["have", "had", "will have"], correct: "had" },
    { id: 'g-mcq-23', type: 'grammar-mcq', questionText: "He can join the club ____ he pays the membership fee.", options: ["unless", "providing that", "although"], correct: "providing that" },
    { id: 'g-mcq-24', type: 'grammar-mcq', questionText: "As long as you ____ focused, you'll reach your destination. (stay)", options: ["stay", "stayed", "staying"], correct: "stay" },
    { id: 'g-mcq-25', type: 'grammar-mcq', questionText: "It's high time she ____ her mistakes. (realize)", options: ["realized", "realize", "realizes"], correct: "realized" },
    { id: 'g-mcq-26', type: 'grammar-mcq', questionText: "If he ____ the instructions, he wouldn't have made a mistake. (follow)", options: ["followed", "had followed", "follows"], correct: "had followed" },
    { id: 'g-mcq-27', type: 'grammar-mcq', questionText: "I wish I ____ how to play the piano.", options: ["know", "knew", "known"], correct: "knew" },
    { id: 'g-mcq-28', type: 'grammar-mcq', questionText: "You can watch TV ____ you finish your homework.", options: ["unless", "as long as", "even though"], correct: "as long as" },
    { id: 'g-mcq-29', type: 'grammar-mcq', questionText: "Providing that he ____ on time, we can start the meeting.", options: ["arrives", "arrived", "will arrive"], correct: "arrives" },
    { id: 'g-mcq-30', type: 'grammar-mcq', questionText: "It's high time we ____ a decision. (make)", options: ["made", "make", "makes"], correct: "made" },
    { id: 'g-mcq-31', type: 'grammar-mcq', questionText: "If I ____ you, I would tell him the truth. (be)", options: ["am", "were", "was"], correct: "were" },
    { id: 'g-mcq-32', type: 'grammar-mcq', questionText: "I wish I ____ a superhero.", options: ["am", "were", "was"], correct: "were" },
    { id: 'g-mcq-33', type: 'grammar-mcq', questionText: "You can pass the exam ____ you study hard.", options: ["unless", "providing that", "in spite of"], correct: "providing that" },
    { id: 'g-mcq-34', type: 'grammar-mcq', questionText: "As long as she ____ healthy, she can play sports. (stay)", options: ["stays", "stayed", "staying"], correct: "stays" },
    { id: 'g-mcq-35', type: 'grammar-mcq', questionText: "It's high time he ____ his responsibilities. (take)", options: ["took", "take", "takes"], correct: "took" },
    { id: 'g-mcq-36', type: 'grammar-mcq', questionText: "If they ____ the game, they would be champions. (win)", options: ["won", "had won", "wins"], correct: "won" },
    { id: 'g-mcq-37', type: 'grammar-mcq', questionText: "I wish I ____ to the party last night.", options: ["went", "had gone", "go"], correct: "had gone" },
    { id: 'g-mcq-38', type: 'grammar-mcq', questionText: "He can succeed ____ he believes in himself.", options: ["unless", "as long as", "despite"], correct: "as long as" },
    { id: 'g-mcq-39', type: 'grammar-mcq', questionText: "Providing that you ____ your promise, I will trust you.", options: ["keep", "kept", "keeping"], correct: "keep" },
    { id: 'g-mcq-40', type: 'grammar-mcq', questionText: "It's high time we ____ this problem. (solve)", options: ["solved", "solve", "solving"], correct: "solved" },
    { id: 'g-mcq-41', type: 'grammar-mcq', questionText: "If I ____ a millionaire, I would buy an island. (be)", options: ["am", "were", "was"], correct: "were" },
    { id: 'g-mcq-42', type: 'grammar-mcq', questionText: "I wish I ____ that mistake.", options: ["didn't make", "hadn't made", "don't make"], correct: "hadn't made" },
    { id: 'g-mcq-43', type: 'grammar-mcq', questionText: "You can eat dessert ____ you finish your main course.", options: ["unless", "providing that", "in case"], correct: "providing that" },
    { id: 'g-mcq-44', type: 'grammar-mcq', questionText: "As long as the sun ____, we can play outside. (shine)", options: ["shines", "shone", "shining"], correct: "shines" },
    { id: 'g-mcq-45', type: 'grammar-mcq', questionText: "It's high time they ____ the truth. (know)", options: ["knew", "know", "knowing"], correct: "knew" },
    { id: 'g-mcq-46', type: 'grammar-mcq', questionText: "If she ____ the answer, she would tell you. (know)", options: ["knew", "knows", "had known"], correct: "knew" },
    { id: 'g-mcq-47', type: 'grammar-mcq', questionText: "I wish I ____ how to swim.", options: ["know", "knew", "known"], correct: "knew" },
    { id: 'g-mcq-48', type: 'grammar-mcq', questionText: "You can get a good grade ____ you study consistently.", options: ["unless", "as long as", "although"], correct: "as long as" },
    { id: 'g-mcq-49', type: 'grammar-mcq', questionText: "Providing that the bus ____ on time, we will make it.", options: ["arrives", "arrived", "will arrive"], correct: "arrives" },
    { id: 'g-mcq-50', type: 'grammar-mcq', questionText: "It's high time we ____ a break. (take)", options: ["took", "take", "taking"], correct: "took" },

    // Final 's' and 'ed' sounds
    { id: 'g-s-1', type: 'grammar-sound', questionText: "Which word has a different final 's' sound?", context: "/s/ vs /z/ vs /iz/", options: ["cats", "dogs", "boxes"], correct: "boxes" },
    { id: 'g-s-2', type: 'grammar-sound', questionText: "Which word has a different final 'ed' sound?", context: "/t/ vs /d/ vs /id/", options: ["walked", "played", "wanted"], correct: "wanted" },
    { id: 'g-s-3', type: 'grammar-sound', questionText: "Which word has a /s/ sound for final 's'?", context: "/s/ vs /z/ vs /iz/", options: ["books", "pens", "watches"], correct: "books" },
    { id: 'g-s-4', type: 'grammar-sound', questionText: "Which word has a /z/ sound for final 's'?", context: "/s/ vs /z/ vs /iz/", options: ["bags", "faces", "cups"], correct: "bags" },
    { id: 'g-s-5', type: 'grammar-sound', questionText: "Which word has an /iz/ sound for final 's'?", context: "/s/ vs /z/ vs /iz/", options: ["maps", "houses", "chairs"], correct: "houses" },
    { id: 'g-s-6', type: 'grammar-sound', questionText: "Which word has a /t/ sound for final 'ed'?", context: "/t/ vs /d/ vs /id/", options: ["stopped", "loved", "needed"], correct: "stopped" },
    { id: 'g-s-7', type: 'grammar-sound', questionText: "Which word has a /d/ sound for final 'ed'?", context: "/t/ vs /d/ vs /id/", options: ["cleaned", "started", "painted"], correct: "cleaned" },
    { id: 'g-s-8', type: 'grammar-sound', questionText: "Which word has an /id/ sound for final 'ed'?", context: "/t/ vs /d/ vs /id/", options: ["asked", "waited", "opened"], correct: "waited" },
    { id: 'g-s-9', type: 'grammar-sound', questionText: "Which word has a different final 's' sound?", context: "/s/ vs /z/ vs /iz/", options: ["lights", "trees", "bushes"], correct: "bushes" },
    { id: 'g-s-10', type: 'grammar-sound', questionText: "Which word has a different final 'ed' sound?", context: "/t/ vs /d/ vs /id/", options: ["cooked", "called", "landed"], correct: "landed" },
    { id: 'g-s-11', type: 'grammar-sound', questionText: "Which word has a /s/ sound for final 's'?", context: "/s/ vs /z/ vs /iz/", options: ["hats", "beds", "dishes"], correct: "hats" },
    { id: 'g-s-12', type: 'grammar-sound', questionText: "Which word has a /z/ sound for final 's'?", context: "/s/ vs /z/ vs /iz/", options: ["tops", "cars", "classes"], correct: "cars" },
    { id: 'g-s-13', type: 'grammar-sound', questionText: "Which word has an /iz/ sound for final 's'?", context: "/s/ vs /z/ vs /iz/", options: ["jokes", "prizes", "walls"], correct: "prizes" },
    { id: 'g-s-14', type: 'grammar-sound', questionText: "Which word has a /t/ sound for final 'ed'?", context: "/t/ vs /d/ vs /id/", options: ["laughed", "lived", "counted"], correct: "laughed" },
    { id: 'g-s-15', type: 'grammar-sound', questionText: "Which word has a /d/ sound for final 'ed'?", context: "/t/ vs /d/ vs /id/", options: ["fixed", "filled", "hunted"], correct: "filled" },
    { id: 'g-s-16', type: 'grammar-sound', questionText: "Which word has an /id/ sound for final 'ed'?", context: "/t/ vs /d/ vs /id/", options: ["jumped", "decided", "shared"], correct: "decided" },
    { id: 'g-s-17', type: 'grammar-sound', questionText: "Which word has a different final 's' sound?", context: "/s/ vs /z/ vs /iz/", options: ["stops", "goes", "washes"], correct: "washes" },
    { id: 'g-s-18', type: 'grammar-sound', questionText: "Which word has a different final 'ed' sound?", context: "/t/ vs /d/ vs /id/", options: ["watched", "opened", "started"], correct: "opened" },
    { id: 'g-s-19', type: 'grammar-sound', questionText: "Which word has a /s/ sound for final 's'?", context: "/s/ vs /z/ vs /iz/", options: ["cups", "songs", "bridges"], correct: "cups" },
    { id: 'g-s-20', type: 'grammar-sound', questionText: "Which word has a /z/ sound for final 's'?", context: "/s/ vs /z/ vs /iz/", options: ["desks", "chairs", "classes"], correct: "chairs" },
    { id: 'g-s-21', type: 'grammar-sound', questionText: "Which word has an /iz/ sound for final 's'?", context: "/s/ vs /z/ vs /iz/", options: ["dates", "faces", "games"], correct: "faces" },
    { id: 'g-s-22', type: 'grammar-sound', questionText: "Which word has a /t/ sound for final 'ed'?", context: "/t/ vs /d/ vs /id/", options: ["missed", "called", "landed"], correct: "missed" },
    { id: 'g-s-23', type: 'grammar-sound', questionText: "Which word has a /d/ sound for final 'ed'?", context: "/t/ vs /d/ vs /id/", options: ["helped", "followed", "waited"], correct: "followed" },
    { id: 'g-s-24', type: 'grammar-sound', questionText: "Which word has an /id/ sound for final 'ed'?", context: "/t/ vs /d/ vs /id/", options: ["worked", "ended", "cleaned"], correct: "ended" },
    { id: 'g-s-25', type: 'grammar-sound', questionText: "Which word has a different final 's' sound?", context: "/s/ vs /z/ vs /iz/", options: ["books", "bags", "dishes"], correct: "dishes" },
    { id: 'g-s-26', type: 'grammar-sound', questionText: "Which word has a different final 'ed' sound?", context: "/t/ vs /d/ vs /id/", options: ["cooked", "played", "started"], correct: "started" },
    { id: 'g-s-27', type: 'grammar-sound', questionText: "Which word has a /s/ sound for final 's'?", context: "/s/ vs /z/ vs /iz/", options: ["stops", "runs", "catches"], correct: "stops" },
    { id: 'g-s-28', type: 'grammar-sound', questionText: "Which word has a /z/ sound for final 's'?", context: "/s/ vs /z/ vs /iz/", options: ["eats", "reads", "kisses"], correct: "reads" },
    { id: 'g-s-29', type: 'grammar-sound', questionText: "Which word has an /iz/ sound for final 's'?", context: "/s/ vs /z/ vs /iz/", options: ["hopes", "closes", "sings"], correct: "closes" },
    { id: 'g-s-30', type: 'grammar-sound', questionText: "Which word has a /t/ sound for final 'ed'?", context: "/t/ vs /d/ vs /id/", options: ["jumped", "loved", "wanted"], correct: "jumped" },
    { id: 'g-s-31', type: 'grammar-sound', questionText: "Which word has a /d/ sound for final 'ed'?", context: "/t/ vs /d/ vs /id/", options: ["talked", "filled", "invited"], correct: "filled" },
    { id: 'g-s-32', type: 'grammar-sound', questionText: "Which word has an /id/ sound for final 'ed'?", context: "/t/ vs /d/ vs /id/", options: ["walked", "waited", "cleaned"], correct: "waited" },
    { id: 'g-s-33', type: 'grammar-sound', questionText: "Which word has a different final 's' sound?", context: "/s/ vs /z/ vs /iz/", options: ["bikes", "cars", "brushes"], correct: "brushes" },
    { id: 'g-s-34', type: 'grammar-sound', questionText: "Which word has a different final 'ed' sound?", context: "/t/ vs /d/ vs /id/", options: ["passed", "followed", "landed"], correct: "landed" },
    { id: 'g-s-35', type: 'grammar-sound', questionText: "Which word has a /s/ sound for final 's'?", context: "/s/ vs /z/ vs /iz/", options: ["hats", "beds", "dishes"], correct: "hats" },
    { id: 'g-s-36', type: 'grammar-sound', questionText: "Which word has a /z/ sound for final 's'?", context: "/s/ vs /z/ vs /iz/", options: ["tops", "cars", "classes"], correct: "cars" },
    { id: 'g-s-37', type: 'grammar-sound', questionText: "Which word has an /iz/ sound for final 's'?", context: "/s/ vs /z/ vs /iz/", options: ["jokes", "prizes", "walls"], correct: "prizes" },
    { id: 'g-s-38', type: 'grammar-sound', questionText: "Which word has a /t/ sound for final 'ed'?", context: "/t/ vs /d/ vs /id/", options: ["laughed", "lived", "counted"], correct: "laughed" },
    { id: 'g-s-39', type: 'grammar-sound', questionText: "Which word has a /d/ sound for final 'ed'?", context: "/t/ vs /d/ vs /id/", options: ["fixed", "filled", "hunted"], correct: "filled" },
    { id: 'g-s-40', type: 'grammar-sound', questionText: "Which word has an /id/ sound for final 'ed'?", context: "/t/ vs /d/ vs /id/", options: ["jumped", "decided", "shared"], correct: "decided" },
    { id: 'g-s-41', type: 'grammar-sound', questionText: "Which word has a different final 's' sound?", context: "/s/ vs /z/ vs /iz/", options: ["stops", "goes", "washes"], correct: "washes" },
    { id: 'g-s-42', type: 'grammar-sound', questionText: "Which word has a different final 'ed' sound?", context: "/t/ vs /d/ vs /id/", options: ["watched", "opened", "started"], correct: "opened" },
    { id: 'g-s-43', type: 'grammar-sound', questionText: "Which word has a /s/ sound for final 's'?", context: "/s/ vs /z/ vs /iz/", options: ["cups", "songs", "bridges"], correct: "cups" },
    { id: 'g-s-44', type: 'grammar-sound', questionText: "Which word has a /z/ sound for final 's'?", context: "/s/ vs /z/ vs /iz/", options: ["desks", "chairs", "classes"], correct: "chairs" },
    { id: 'g-s-45', type: 'grammar-sound', questionText: "Which word has an /iz/ sound for final 's'?", context: "/s/ vs /z/ vs /iz/", options: ["dates", "faces", "games"], correct: "faces" },
    { id: 'g-s-46', type: 'grammar-sound', questionText: "Which word has a /t/ sound for final 'ed'?", context: "/t/ vs /d/ vs /id/", options: ["missed", "called", "landed"], correct: "missed" },
    { id: 'g-s-47', type: 'grammar-sound', questionText: "Which word has a /d/ sound for final 'ed'?", context: "/t/ vs /d/ vs /id/", options: ["helped", "followed", "waited"], correct: "followed" },
    { id: 'g-s-48', type: 'grammar-sound', questionText: "Which word has an /id/ sound for final 'ed'?", context: "/t/ vs /d/ vs /id/", options: ["worked", "ended", "cleaned"], correct: "ended" },
    { id: 'g-s-49', type: 'grammar-sound', questionText: "Which word has a different final 's' sound?", context: "/s/ vs /z/ vs /iz/", options: ["bikes", "cars", "brushes"], correct: "brushes" },
    { id: 'g-s-50', type: 'grammar-sound', questionText: "Which word has a different final 'ed' sound?", context: "/t/ vs /d/ vs /id/", options: ["passed", "followed", "landed"], correct: "landed" },
  ];

  const startIndex = (levelNum - 1) * 15;
  const endIndex = startIndex + 15;
  const selectedQuestions = allGrammarQuestions.slice(startIndex, endIndex);

  return selectedQuestions.map((q, idx) => ({
    ...q,
    id: `eng-g${levelNum}-${q.id.split('-').slice(1).join('-')}-${idx}`
  }));
};

// دالة مساعدة لإنشاء أسئلة مفردات فريدة لكل مستوى (أخلاقيات)
const generateEthicsQuestions = (levelNum: number): Question[] => {
  const terms = [
    { word: 'Ethics', ar: 'الأخلاق' }, { word: 'Governments', ar: 'الحكومات' }, { word: 'Employee', ar: 'موظف' },
    { word: 'Corruption', ar: 'الفساد' }, { word: 'Child Labor', ar: 'عمل الأطفال' }, { word: 'Bribery', ar: 'الرشوة' },
    { word: 'Embezzlement', ar: 'اختلاس المال' }, { word: 'Honest', ar: 'صادق' }, { word: 'Corrupt', ar: 'فاسد' },
    { word: 'Trust', ar: 'الثقة' }, { word: 'Responsibility', ar: 'المسؤولية' }, { word: 'Professional', ar: 'محترف' },
    { word: 'Workplace', ar: 'مكان العمل' }, { word: 'Fair', ar: 'عادل' }, { word: 'Justice', ar: 'العدالة' },
    { word: 'Integrity', ar: 'النزاهة' }, { word: 'Transparency', ar: 'الشفافية' }, { word: 'Accountability', ar: 'المساءلة' },
    { word: 'Compliance', ar: 'الامتثال' }, { word: 'Misconduct', ar: 'سوء السلوك' }, { word: 'Harassment', ar: 'التحرش' },
    { word: 'Discrimination', ar: 'التمييز' }, { word: 'Fraud', ar: 'الاحتيال' }, { word: 'Whistleblowing', ar: 'كشف المخالفات' },
    { word: 'Code of Conduct', ar: 'قواعد السلوك' }, { word: 'Conflict of Interest', ar: 'تضارب المصالح' }, { word: 'Due Diligence', ar: 'العناية الواجبة' },
    { word: 'Good Governance', ar: 'الحكم الرشيد' }, { word: 'Stakeholder', ar: 'أصحاب المصلحة' }, { word: 'Corporate Social Responsibility', ar: 'المسؤولية الاجتماعية للشركات' },
    { word: 'Sustainability', ar: 'الاستدامة' }, { word: 'Environmental Ethics', ar: 'أخلاقيات البيئة' }, { word: 'Fair Trade', ar: 'التجارة العادلة' },
    { word: 'Labor Standards', ar: 'معايير العمل' }, { word: 'Work-Life Balance', ar: 'توازن العمل والحياة' },
    { word: 'Human Rights', ar: 'حقوق الإنسان' }, { word: 'Exploitation', ar: 'الاستغلال' }, { word: 'Diversity', ar: 'التنوع' },
    { word: 'Inclusion', ar: 'الاندماج' }, { word: 'Ethical Dilemma', ar: 'معضلة أخلاقية' }, { word: 'Moral Values', ar: 'القيم الأخلاقية' },
    { word: 'Reputation', ar: 'السمعة' }, { word: 'Sanctions', ar: 'العقوبات' }, { word: 'Regulation', ar: 'التنظيم' },
    { word: 'Legislation', ar: 'التشريع' }, { word: 'Consumer Rights', ar: 'حقوق المستهلك' }, { word: 'Privacy', ar: 'الخصوصية' },
    { word: 'Data Protection', ar: 'حماية البيانات' }, { word: 'Cybersecurity', ar: 'الأمن السيبراني' }, { word: 'Intellectual Property', ar: 'الملكية الفكرية' },
    { word: 'Patent', ar: 'براءة اختراع' }, { word: 'Trademark', ar: 'علامة تجارية' }, { word: 'Copyright', ar: 'حقوق النشر' },
    { word: 'Confidentiality', ar: 'السرية' }, { word: 'Conflict Resolution', ar: 'حل النزاعات' }, { word: 'Mediation', ar: 'الوساطة' },
    { word: 'Arbitration', ar: 'التحكيم' }, { word: 'Negotiation', ar: 'التفاوض' }, { word: 'Collective Bargaining', ar: 'المفاوضة الجماعية' },
    { word: 'Union', ar: 'نقابة' }, { word: 'Strike', ar: 'إضراب' }, { word: 'Lockout', ar: 'إغلاق المصنع' },
    { word: 'Dismissal', ar: 'الفصل' }, { word: 'Resignation', ar: 'الاستقالة' }, { word: 'Retirement', ar: 'التقاعد' },
    { word: 'Pension', ar: 'معاش تقاعدي' }, { word: 'Insurance', ar: 'تأمين' }, { word: 'Healthcare', ar: 'الرعاية الصحية' },
    { word: 'Welfare', ar: 'الرفاهية' }, { word: 'Social Justice', ar: 'العدالة الاجتماعية' }, { word: 'Equality', ar: 'المساواة' },
    { word: 'Equity', ar: 'الإنصاف' }, { word: 'Empowerment', ar: 'التمكين' }, { word: 'Philanthropy', ar: 'العمل الخيري' },
    { word: 'Donation', ar: 'تبرع' }, { word: 'Volunteer', ar: 'متطوع' }, { word: 'Community Service', ar: 'الخدمة المجتمعية' },
    { word: 'Charity', ar: 'جمعية خيرية' }, { word: 'Non-profit', ar: 'غير ربحي' }, { word: 'For-profit', ar: 'ربحي' },
    { word: 'Social Enterprise', ar: 'مؤسسة اجتماعية' }, { word: 'Impact Investing', ar: 'الاستثمار المؤثر' }, { word: 'Greenwashing', ar: 'الغسل الأخضر' },
    { word: 'Ethical Sourcing', ar: 'المصادر الأخلاقية' }, { word: 'Supply Chain', ar: 'سلسلة التوريد' }, { word: 'Fair Wages', ar: 'الأجور العادلة' },
    { word: 'Safe Working Conditions', ar: 'ظروف عمل آمنة' }, { word: 'Child Protection', ar: 'حماية الأطفال' }, { word: 'Human Trafficking', ar: 'الاتجار بالبشر' },
    { word: 'Forced Labor', ar: 'العمل القسري' }, { word: 'Modern Slavery', ar: 'العبودية الحديثة' }, { word: 'Due Process', ar: 'الإجراءات القانونية الواجبة' },
    { word: 'Rule of Law', ar: 'سيادة القانون' }, { word: 'Human Dignity', ar: 'الكرامة الإنسانية' }, { word: 'Moral Compass', ar: 'البوصلة الأخلاقية' },
    { word: 'Conscience', ar: 'الضمير' }, { word: 'Virtue', ar: 'الفضيلة' }, { word: 'Vice', ar: 'الرذيلة' },
    { word: 'Integrity', ar: 'النزاهة' }, { word: 'Honesty', ar: 'الصدق' }, { word: 'Respect', ar: 'الاحترام' },
    { word: 'Responsibility', ar: 'المسؤولية' }, { word: 'Courage', ar: 'الشجاعة' }, { word: 'Compassion', ar: 'التعاطف' },
    { word: 'Empathy', ar: 'التعاطف' }, { word: 'Kindness', ar: 'اللطف' }, { word: 'Generosity', ar: 'الكرم' },
    { word: 'Patience', ar: 'الصبر' }, { word: 'Perseverance', ar: 'المثابرة' }, { word: 'Resilience', ar: 'المرونة' },
    { word: 'Adaptability', ar: 'القدرة على التكيف' }, { word: 'Creativity', ar: 'الإبداع' }, { word: 'Innovation', ar: 'الابتكار' },
    { word: 'Critical Thinking', ar: 'التفكير النقدي' }, { word: 'Problem Solving', ar: 'حل المشكلات' }, { word: 'Decision Making', ar: 'اتخاذ القرار' },
    { word: 'Leadership', ar: 'القيادة' }, { word: 'Teamwork', ar: 'العمل الجماعي' }, { word: 'Communication', ar: 'التواصل' },
    { word: 'Active Listening', ar: 'الاستماع النشط' }, { word: 'Feedback', ar: 'التغذية الراجعة' }, { word: 'Conflict Management', ar: 'إدارة النزاعات' },
    { word: 'Negotiation Skills', ar: 'مهارات التفاوض' }, { word: 'Public Speaking', ar: 'الخطابة' }, { word: 'Presentation Skills', ar: 'مهارات العرض' },
    { word: 'Time Management', ar: 'إدارة الوقت' }, { word: 'Stress Management', ar: 'إدارة الإجهاد' }, { word: 'Self-awareness', ar: 'الوعي الذاتي' },
    { word: 'Self-regulation', ar: 'التنظيم الذاتي' }, { word: 'Motivation', ar: 'التحفيز' }, { word: 'Goal Setting', ar: 'تحديد الأهداف' },
    { word: 'Planning', ar: 'التخطيط' }, { word: 'Execution', ar: 'التنفيذ' }, { word: 'Evaluation', ar: 'التقييم' },
    { word: 'Continuous Learning', ar: 'التعلم المستمر' }, { word: 'Growth Mindset', ar: 'عقلية النمو' }, { word: 'Fixed Mindset', ar: 'عقلية ثابتة' },
    { word: 'Emotional Intelligence', ar: 'الذكاء العاطفي' }, { word: 'Social Skills', ar: 'المهارات الاجتماعية' }, { word: 'Interpersonal Skills', ar: 'المهارات الشخصية' },
    { word: 'Cross-cultural Communication', ar: 'التواصل بين الثقافات' }, { word: 'Global Citizenship', ar: 'المواطنة العالمية' }, { word: 'Ethical Leadership', ar: 'القيادة الأخلاقية' },
    { word: 'Servant Leadership', ar: 'القيادة الخادمة' }, { word: 'Transformational Leadership', ar: 'القيادة التحويلية' }, { word: 'Authentic Leadership', ar: 'القيادة الأصيلة' },
    { word: 'Visionary Leadership', ar: 'القيادة البصيرة' }, { word: 'Strategic Thinking', ar: 'التفكير الاستراتيجي' }, { word: 'Risk Management', ar: 'إدارة المخاطر' },
    { word: 'Crisis Management', ar: 'إدارة الأزمات' }, { word: 'Change Management', ar: 'إدارة التغيير' }, { word: 'Innovation Management', ar: 'إدارة الابتكار' },
    { word: 'Quality Management', ar: 'إدارة الجودة' }, { word: 'Project Management', ar: 'إدارة المشاريع' }, { word: 'Financial Management', ar: 'الإدارة المالية' },
    { word: 'Marketing Ethics', ar: 'أخلاقيات التسويق' }, { word: 'Advertising Ethics', ar: 'أخلاقيات الإعلان' }, { word: 'Sales Ethics', ar: 'أخلاقيات المبيعات' },
    { word: 'Customer Service Ethics', ar: 'أخلاقيات خدمة العملاء' }, { word: 'Product Safety', ar: 'سلامة المنتج' }, { word: 'Environmental Protection', ar: 'حماية البيئة' },
    { word: 'Resource Depletion', ar: 'استنزاف الموارد' }, { word: 'Pollution', ar: 'التلوث' }, { word: 'Climate Change', ar: 'تغير المناخ' },
    { word: 'Renewable Energy', ar: 'الطاقة المتجددة' }, { word: 'Sustainable Development', ar: 'التنمية المستدامة' }, { word: 'Circular Economy', ar: 'الاقتصاد الدائري' },
    { word: 'Waste Management', ar: 'إدارة النفايات' }, { word: 'Recycling', ar: 'إعادة التدوير' }, { word: 'Upcycling', ar: 'إعادة التدوير الإبداعي' },
    { word: 'Green Technology', ar: 'التكنولوجيا الخضراء' }, { word: 'Eco-friendly', ar: 'صديق للبيئة' }, { word: 'Carbon Footprint', ar: 'البصمة الكربونية' },
    { word: 'Biodiversity', ar: 'التنوع البيولوجي' }, { word: 'Conservation', ar: 'الحفاظ على البيئة' }, { word: 'Restoration', ar: 'الاستعادة البيئية' },
    { word: 'Wildlife Protection', ar: 'حماية الحياة البرية' }, { word: 'Animal Welfare', ar: 'رفاهية الحيوان' }, { word: 'Ethical Consumerism', ar: 'الاستهلاك الأخلاقي' },
    { word: 'Fair Trade Certification', ar: 'شهادة التجارة العادلة' }, { word: 'Organic Farming', ar: 'الزراعة العضوية' }, { word: 'GMOs', ar: 'الكائنات المعدلة وراثيا' },
    { word: 'Food Waste', ar: 'هدر الطعام' }, { word: 'Food Security', ar: 'الأمن الغذائي' }, { word: 'Water Scarcity', ar: 'ندرة المياه' },
    { word: 'Access to Education', ar: 'الوصول إلى التعليم' }, { word: 'Healthcare Access', ar: 'الوصول إلى الرعاية الصحية' }, { word: 'Poverty Alleviation', ar: 'تخفيف الفقر' },
    { word: 'Income Inequality', ar: 'عدم المساواة في الدخل' }, { word: 'Wealth Distribution', ar: 'توزيع الثروة' }, { word: 'Social Mobility', ar: 'الحراك الاجتماعي' },
    { word: 'Affirmative Action', ar: 'التمييز الإيجابي' }, { word: 'Gender Equality', ar: 'المساواة بين الجنسين' }, { word: 'Racial Justice', ar: 'العدالة العرقية' },
    { word: 'Religious Freedom', ar: 'الحرية الدينية' }, { word: 'Freedom of Speech', ar: 'حرية التعبير' }, { word: 'Humanitarian Aid', ar: 'المساعدات الإنسانية' },
    { word: 'Disaster Relief', ar: 'الإغاثة من الكوارث' }, { word: 'Refugee Crisis', ar: 'أزمة اللاجئين' }, { word: 'Migration', ar: 'الهجرة' },
    { word: 'Asylum Seeker', ar: 'طالب اللجوء' }, { word: 'Stateless Person', ar: 'شخص عديم الجنسية' }, { word: 'International Law', ar: 'القانون الدولي' },
    { word: 'War Crimes', ar: 'جرائم الحرب' }, { word: 'Genocide', ar: 'الإبادة الجماعية' }, { word: 'Crimes Against Humanity', ar: 'جرائم ضد الإنسانية' },
    { word: 'Peacekeeping', ar: 'حفظ السلام' }, { word: 'Diplomacy', ar: 'الدبلوماسية' }, { word: 'Treaty', ar: 'معاهدة' },
    { word: 'Alliance', ar: 'تحالف' }, { word: 'Sanctions', ar: 'عقوبات' }, { word: 'Embargo', ar: 'حظر تجاري' },
    { word: 'Boycott', ar: 'مقاطعة' }, { word: 'Protest', ar: 'احتجاج' }, { word: 'Activism', ar: 'النشاط' },
    { word: 'Advocacy', ar: 'الدعوة' }, { word: 'Lobbying', ar: 'الضغط' }, { word: 'Transparency International', ar: 'الشفافية الدولية' },
    { word: 'Amnesty International', ar: 'منظمة العفو الدولية' }, { word: 'Doctors Without Borders', ar: 'أطباء بلا حدود' }, { word: 'Red Cross', ar: 'الصليب الأحمر' },
    { word: 'United Nations', ar: 'الأمم المتحدة' }, { word: 'World Bank', ar: 'البنك الدولي' }, { word: 'International Monetary Fund', ar: 'صندوق النقد الدولي' },
    { word: 'World Trade Organization', ar: 'منظمة التجارة العالمية' }, { word: 'G20', ar: 'مجموعة العشرين' }, { word: 'G7', ar: 'مجموعة السبع' },
    { word: 'NATO', ar: 'الناتو' }, { word: 'European Union', ar: 'الاتحاد الأوروبي' }, { word: 'African Union', ar: 'الاتحاد الأفريقي' },
    { word: 'Arab League', ar: 'الجامعة العربية' }, { word: 'OPEC', ar: 'أوبك' }, { word: 'ASEAN', ar: 'آسيان' },
    { word: 'BRICS', ar: 'بريكس' }, { word: 'SCO', ar: 'منظمة شنغهاي للتعاون' }, { word: 'UNICEF', ar: 'اليونيسف' },
    { word: 'WHO', ar: 'منظمة الصحة العالمية' }, { word: 'UNESCO', ar: 'اليونسكو' }, { word: 'IMF', ar: 'صندوق النقد الدولي' },
    { word: 'ILO', ar: 'منظمة العمل الدولية' }, { word: 'WTO', ar: 'منظمة التجارة العالمية' }, { word: 'ICC', ar: 'المحكمة الجنائية الدولية' },
    { word: 'ICJ', ar: 'محكمة العدل الدولية' }, { word: 'Humanitarian Intervention', ar: 'التدخل الإنساني' }, { word: 'Responsibility to Protect (R2P)', ar: 'مسؤولية الحماية' },
    { word: 'Sovereignty', ar: 'السيادة' }, { word: 'Non-interference', ar: 'عدم التدخل' }, { word: 'Self-determination', ar: 'تقرير المصير' },
    { word: 'National Interest', ar: 'المصلحة الوطنية' }, { word: 'Geopolitics', ar: 'الجغرافيا السياسية' }, { word: 'International Relations', ar: 'العلاقات الدولية' },
    { word: 'Soft Power', ar: 'القوة الناعمة' }, { word: 'Hard Power', ar: 'القوة الصلبة' }, { word: 'Smart Power', ar: 'القوة الذكية' },
    { word: 'Public Diplomacy', ar: 'الدبلوماسية العامة' }, { word: 'Cultural Exchange', ar: 'التبادل الثقافي' }, { word: 'Economic Diplomacy', ar: 'الدبلوماسية الاقتصادية' },
    { word: 'Digital Diplomacy', ar: 'الدبلوماسية الرقمية' }, { word: 'Cyber Diplomacy', ar: 'الدبلوماسية السيبرانية' }, { word: 'Climate Diplomacy', ar: 'دبلوماسية المناخ' },
    { word: 'Health Diplomacy', ar: 'دبلوماسية الصحة' }, { word: 'Science Diplomacy', ar: 'دبلوماسية العلوم' }, { word: 'Sports Diplomacy', ar: 'دبلوماسية الرياضة' },
    { word: 'Citizen Diplomacy', ar: 'دبلوماسية المواطنين' }, { word: 'Track Two Diplomacy', ar: 'دبلوماسية المسار الثاني' }, { word: 'Multilateralism', ar: 'التعددية' },
    { word: 'Bilateralism', ar: 'الثنائية' }, { word: 'Unilateralism', ar: 'الأحادية' }, { word: 'Global Governance', ar: 'الحوكمة العالمية' },
    { word: 'International Cooperation', ar: 'التعاون الدولي' }, { word: 'Global Challenges', ar: 'التحديات العالمية' }, { word: 'Sustainable Development Goals (SDGs)', ar: 'أهداف التنمية المستدامة' },
    { word: 'Poverty', ar: 'الفقر' }, { word: 'Hunger', ar: 'الجوع' }, { word: 'Good Health', ar: 'الصحة الجيدة' },
    { word: 'Quality Education', ar: 'التعليم الجيد' }, { word: 'Gender Equality', ar: 'المساواة بين الجنسين' }, { word: 'Clean Water', ar: 'المياه النظيفة' },
    { word: 'Affordable Energy', ar: 'الطاقة النظيفة بأسعار معقولة' }, { word: 'Decent Work', ar: 'العمل اللائق' }, { word: 'Industry, Innovation, Infrastructure', ar: 'الصناعة والابتكار والبنية التحتية' },
    { word: 'Reduced Inequalities', ar: 'الحد من عدم المساواة' }, { word: 'Sustainable Cities', ar: 'مدن ومجتمعات مستدامة' }, { word: 'Responsible Consumption', ar: 'الاستهلاك والإنتاج المسؤولان' },
    { word: 'Climate Action', ar: 'العمل المناخي' }, { word: 'Life Below Water', ar: 'الحياة تحت الماء' }, { word: 'Life on Land', ar: 'الحياة في البر' },
    { word: 'Peace, Justice, Strong Institutions', ar: 'السلام والعدل والمؤسسات القوية' }, { word: 'Partnerships for the Goals', ar: 'الشراكات من أجل الأهداف' },
  ];

  const startIndex = (levelNum - 1) * 15;
  const selectedTerms = terms.slice(startIndex, startIndex + 15);

  return selectedTerms.map((term, index) => {
    const incorrectOptions = shuffleArray(terms.filter(t => t.ar !== term.ar).map(t => t.ar)).slice(0, 2);
    return {
      id: `eng-e${levelNum}-q${index + 1}`,
      type: 'word-translation',
      questionText: term.word,
      options: shuffleArray([term.ar, ...incorrectOptions]),
      correct: term.ar,
    };
  });
};

// دالة مساعدة لإنشاء أسئلة مفردات فريدة لكل مستوى (السلامة أولاً)
const generateSafetyQuestions = (levelNum: number): Question[] => {
  const terms = [
    { word: 'Fat', ar: 'دهون' }, { word: 'Sugar', ar: 'سكر' }, { word: 'Ads', ar: 'إعلانات' },
    { word: 'Ill', ar: 'مريض' }, { word: 'Fast food', ar: 'طعام سريع' }, { word: 'Fake advertising', ar: 'إعلانات كاذبة' },
    { word: 'Vegetables', ar: 'خضروات' }, { word: 'Fruits', ar: 'فواكه' }, { word: 'Meat', ar: 'لحم' },
    { word: 'Milk', ar: 'حليب' }, { word: 'Healthy', ar: 'صحي' }, { word: 'Unhealthy', ar: 'غير صحي' },
    { word: 'Obesity', ar: 'السمنة' }, { word: 'Nutrition', ar: 'التغذية' }, { word: 'Exercise', ar: 'تمارين' },
    { word: 'Protein', ar: 'بروتين' }, { word: 'Carbohydrates', ar: 'كربوهيدرات' }, { word: 'Minerals', ar: 'معادن' },
    { word: 'Fiber', ar: 'ألياف' }, { word: 'Antioxidants', ar: 'مضادات الأكسدة' }, { word: 'Metabolism', ar: 'عملية الأيض' },
    { word: 'Processed Food', ar: 'الطعام المعالج' }, { word: 'Whole Grains', ar: 'الحبوب الكاملة' }, { word: 'Cholesterol', ar: 'الكوليسترول' },
    { word: 'Blood Pressure', ar: 'ضغط الدم' }, { word: 'Immune System', ar: 'جهاز المناعة' }, { word: 'Hydration', ar: 'الترطيب' },
    { word: 'Portion Control', ar: 'التحكم في الحصص' }, { word: 'Food Pyramid', ar: 'هرم الغذاء' }, { word: 'Eating Disorder', ar: 'اضطراب الأكل' },
    { word: 'Nutritional Value', ar: 'القيمة الغذائية' }, { word: 'Food Safety', ar: 'سلامة الغذاء' }, { word: 'Dietary Supplement', ar: 'مكمل غذائي' },
    { word: 'Gluten-Free', ar: 'خالي من الجلوتين' }, { word: 'Organic', ar: 'عضوي' }, { word: 'Additives', ar: 'إضافات غذائية' },
    { word: 'Preservatives', ar: 'مواد حافظة' }, { word: 'Artificial Sweeteners', ar: 'محليات صناعية' }, { word: 'Trans Fats', ar: 'الدهون المتحولة' },
    { word: 'Saturated Fats', ar: 'الدهون المشبعة' }, { word: 'Unsaturated Fats', ar: 'الدهون غير المشبعة' }, { word: 'Vitamins', ar: 'فيتامينات' },
    { word: 'Calories', ar: 'سعرات حرارية' }, { word: 'Balanced Diet', ar: 'نظام غذائي متوازن' }, { word: 'Water Intake', ar: 'كمية الماء المتناولة' },
    { word: 'Food Poisoning', ar: 'التسمم الغذائي' }, { word: 'Allergies', ar: 'حساسية الطعام' }, { word: 'Intolerance', ar: 'عدم تحمل الطعام' },
    { word: 'Cross-contamination', ar: 'التلوث المتبادل' }, { word: 'Expiration Date', ar: 'تاريخ انتهاء الصلاحية' }, { word: 'Best Before Date', ar: 'أفضل قبل تاريخ' },
    { word: 'Food Labeling', ar: 'تسميات الغذاء' }, { word: 'Genetically Modified Organisms (GMOs)', ar: 'الكائنات المعدلة وراثيا' }, { word: 'Pesticides', ar: 'المبيدات الحشرية' },
    { word: 'Herbicides', ar: 'مبيدات الأعشاب' }, { word: 'Antibiotics in Food', ar: 'المضادات الحيوية في الغذاء' }, { word: 'Hormones in Food', ar: 'الهرمونات في الغذاء' },
    { word: 'Processed Meat', ar: 'اللحوم المصنعة' }, { word: 'Red Meat', ar: 'اللحوم الحمراء' }, { word: 'White Meat', ar: 'اللحوم البيضاء' },
    { word: 'Fish', ar: 'الأسماك' }, { word: 'Poultry', ar: 'الدواجن' }, { word: 'Legumes', ar: 'البقوليات' },
    { word: 'Nuts', ar: 'المكسرات' }, { word: 'Seeds', ar: 'البذور' }, { word: 'Dairy Products', ar: 'منتجات الألبان' },
    { word: 'Eggs', ar: 'البيض' }, { word: 'Grains', ar: 'الحبوب' }, { word: 'Whole Foods', ar: 'الأطعمة الكاملة' },
    { word: 'Refined Grains', ar: 'الحبوب المكررة' }, { word: 'Empty Calories', ar: 'سعرات حرارية فارغة' }, { word: 'Sugary Drinks', ar: 'المشروبات السكرية' },
    { word: 'Artificial Colors', ar: 'ألوان صناعية' }, { word: 'Artificial Flavors', ar: 'نكهات صناعية' }, { word: 'Monosodium Glutamate (MSG)', ar: 'غلوتامات أحادية الصوديوم' },
    { word: 'High Fructose Corn Syrup', ar: 'شراب الذرة عالي الفركتوز' }, { word: 'Hydrogenated Oils', ar: 'الزيوت المهدرجة' }, { word: 'Omega-3 Fatty Acids', ar: 'أحماض أوميغا 3 الدهنية' },
    { word: 'Probiotics', ar: 'البروبيوتيك' }, { word: 'Prebiotics', ar: 'البريبايوتكس' }, { word: 'Gut Health', ar: 'صحة الأمعاء' },
    { word: 'Microbiome', ar: 'الميكروبيوم' }, { word: 'Digestive System', ar: 'الجهاز الهضمي' }, { word: 'Immunity', ar: 'المناعة' },
    { word: 'Inflammation', ar: 'الالتهاب' }, { word: 'Chronic Diseases', ar: 'الأمراض المزمنة' }, { word: 'Cardiovascular Disease', ar: 'أمراض القلب والأوعية الدموية' },
    { word: 'Hypertension', ar: 'ارتفاع ضغط الدم' }, { word: 'Stroke', ar: 'السكتة الدماغية' }, { word: 'Cancer', ar: 'السرطان' },
    { word: 'Type 2 Diabetes', ar: 'السكري من النوع 2' }, { word: 'Mental Health', ar: 'الصحة العقلية' }, { word: 'Depression', ar: 'الاكتئاب' },
    { word: 'Anxiety', ar: 'القلق' }, { word: 'Stress', ar: 'الإجهاد' }, { word: 'Mindful Eating', ar: 'الأكل الواعي' },
    { word: 'Intuitive Eating', ar: 'الأكل الحدسي' }, { word: 'Body Image', ar: 'صورة الجسم' }, { word: 'Self-esteem', ar: 'تقدير الذات' },
    { word: 'Weight Management', ar: 'إدارة الوزن' }, { word: 'Metabolic Rate', ar: 'معدل الأيض' }, { word: 'Basal Metabolic Rate (BMR)', ar: 'معدل الأيض الأساسي' },
    { word: 'Thermic Effect of Food (TEF)', ar: 'التأثير الحراري للطعام' }, { word: 'Physical Activity', ar: 'النشاط البدني' }, { word: 'Sedentary Lifestyle', ar: 'نمط الحياة الخامل' },
    { word: 'Aerobic Exercise', ar: 'التمارين الهوائية' }, { word: 'Strength Training', ar: 'تدريب القوة' }, { word: 'Flexibility', ar: 'المرونة' },
    { word: 'Endurance', ar: 'التحمل' }, { word: 'Warm-up', ar: 'الإحماء' }, { word: 'Cool-down', ar: 'التهدئة' },
    { word: 'Hydration Status', ar: 'حالة الترطيب' }, { word: 'Electrolytes', ar: 'الكهارل' }, { word: 'Dehydration', ar: 'الجفاف' },
    { word: 'Overhydration', ar: 'الإفراط في الترطيب' }, { word: 'Foodborne Illness', ar: 'الأمراض المنقولة بالغذاء' }, { word: 'Hygiene', ar: 'النظافة' },
    { word: 'Handwashing', ar: 'غسل اليدين' }, { word: 'Cooking Temperature', ar: 'درجة حرارة الطهي' }, { word: 'Refrigeration', ar: 'التبريد' },
    { word: 'Freezing', ar: 'التجميد' }, { word: 'Cross-contamination Prevention', ar: 'منع التلوث المتبادل' }, { word: 'Food Storage', ar: 'تخزين الطعام' },
    { word: 'Shelf Life', ar: 'مدة الصلاحية' }, { word: 'Food Additive Safety', ar: 'سلامة المضافات الغذائية' }, { word: 'Food Packaging', ar: 'تعبئة الطعام' },
    { word: 'Sustainable Food Systems', ar: 'أنظمة غذائية مستدامة' }, { word: 'Local Food', ar: 'الغذاء المحلي' }, { word: 'Seasonal Food', ar: 'الغذاء الموسمي' },
    { word: 'Food Waste Reduction', ar: 'الحد من هدر الطعام' }, { word: 'Composting', ar: 'التسميد العضوي' }, { word: 'Food Recovery', ar: 'استعادة الطعام' },
    { word: 'Food Donation', ar: 'التبرع بالطعام' }, { word: 'Community Gardens', ar: 'حدائق المجتمع' }, { word: 'Urban Farming', ar: 'الزراعة الحضرية' },
    { word: 'Vertical Farming', ar: 'الزراعة العمودية' }, { word: 'Hydroponics', ar: 'الزراعة المائية' }, { word: 'Aquaponics', ar: 'الزراعة المائية المتكاملة' },
    { word: 'Sustainable Agriculture', ar: 'الزراعة المستدامة' }, { word: 'Agroecology', ar: 'الزراعة الإيكولوجية' }, { word: 'Permaculture', ar: 'الزراعة المعمرة' },
    { word: 'Food Policy', ar: 'السياسة الغذائية' }, { word: 'Food Security Policy', ar: 'سياسة الأمن الغذائي' }, { word: 'Public Health', ar: 'الصحة العامة' },
    { word: 'Epidemiology', ar: 'علم الأوبئة' }, { word: 'Pandemic', ar: 'جائحة' }, { word: 'Endemic', ar: 'متوطن' },
    { word: 'Outbreak', ar: 'تفشي المرض' }, { word: 'Vaccination', ar: 'التطعيم' }, { word: 'Immunization', ar: 'التحصين' },
    { word: 'Herd Immunity', ar: 'مناعة القطيع' }, { word: 'Public Health Campaigns', ar: 'حملات الصحة العامة' }, { word: 'Health Education', ar: 'التثقيف الصحي' },
    { word: 'Health Promotion', ar: 'تعزيز الصحة' }, { word: 'Disease Prevention', ar: 'الوقاية من الأمراض' }, { word: 'Early Detection', ar: 'الكشف المبكر' },
    { word: 'Screening', ar: 'الفحص' }, { word: 'Treatment', ar: 'العلاج' }, { word: 'Rehabilitation', ar: 'إعادة التأهيل' },
    { word: 'Palliative Care', ar: 'الرعاية التلطيفية' }, { word: 'Hospice Care', ar: 'رعاية المحتضرين' }, { word: 'Universal Healthcare', ar: 'الرعاية الصحية الشاملة' },
    { word: 'Health Equity', ar: 'الإنصاف في الصحة' }, { word: 'Health Disparities', ar: 'الفوارق الصحية' }, { word: 'Social Determinants of Health', ar: 'المحددات الاجتماعية للصحة' },
    { word: 'Health Literacy', ar: 'الثقافة الصحية' }, { word: 'Patient Rights', ar: 'حقوق المريض' }, { word: 'Informed Consent', ar: 'الموافقة المستنيرة' },
    { word: 'Medical Ethics', ar: 'أخلاقيات الطب' }, { word: 'Bioethics', ar: 'الأخلاقيات البيولوجية' }, { word: 'Clinical Trials', ar: 'التجارب السريرية' },
    { word: 'Drug Development', ar: 'تطوير الأدوية' }, { word: 'Pharmaceutical Industry', ar: 'صناعة الأدوية' }, { word: 'Medical Devices', ar: 'الأجهزة الطبية' },
    { word: 'Telemedicine', ar: 'الطب عن بعد' }, { word: 'Digital Health', ar: 'الصحة الرقمية' }, { word: 'Artificial Intelligence in Healthcare', ar: 'الذكاء الاصطناعي في الرعاية الصحية' },
    { word: 'Big Data in Healthcare', ar: 'البيانات الضخمة في الرعاية الصحية' }, { word: 'Personalized Medicine', ar: 'الطب الشخصي' }, { word: 'Genomic Medicine', ar: 'الطب الجيني' },
    { word: 'Precision Medicine', ar: 'الطب الدقيق' }, { word: 'Health Technology Assessment', ar: 'تقييم التكنولوجيا الصحية' }, { word: 'Health Policy', ar: 'السياسة الصحية' },
    { word: 'Health Economics', ar: 'اقتصاديات الصحة' }, { word: 'Health Systems', ar: 'الأنظمة الصحية' }, { word: 'Primary Healthcare', ar: 'الرعاية الصحية الأولية' },
    { word: 'Secondary Healthcare', ar: 'الرعاية الصحية الثانوية' }, { word: 'Tertiary Healthcare', ar: 'الرعاية الصحية الثالثية' }, { word: 'Hospital Management', ar: 'إدارة المستشفيات' },
    { word: 'Nursing', ar: 'التمريض' }, { word: 'Physician', ar: 'طبيب' }, { word: 'Pharmacist', ar: 'صيدلي' },
    { word: 'Dentist', ar: 'طبيب أسنان' }, { word: 'Therapist', ar: 'معالج' }, { word: 'Psychologist', ar: 'عالم نفس' },
    { word: 'Psychiatrist', ar: 'طبيب نفسي' }, { word: 'Nutritionist', ar: 'أخصائي تغذية' }, { word: 'Dietitian', ar: 'أخصائي تغذية علاجية' },
    { word: 'Fitness Instructor', ar: 'مدرب لياقة بدنية' }, { word: 'Personal Trainer', ar: 'مدرب شخصي' }, { word: 'Sports Medicine', ar: 'الطب الرياضي' },
    { word: 'Recreational Activities', ar: 'الأنشطة الترفيهية' }, { word: 'Outdoor Activities', ar: 'الأنشطة الخارجية' }, { word: 'Leisure Time', ar: 'وقت الفراغ' },
    { word: 'Work-Life Balance', ar: 'توازن العمل والحياة' }, { word: 'Burnout', ar: 'الإرهاق' }, { word: 'Stress Relief', ar: 'تخفيف التوتر' },
    { word: 'Relaxation Techniques', ar: 'تقنيات الاسترخاء' }, { word: 'Mindfulness', ar: 'اليقظة الذهنية' }, { word: 'Meditation', ar: 'التأمل' },
    { word: 'Yoga', ar: 'اليوغا' }, { word: 'Pilates', ar: 'البلاتس' }, { word: 'Zumba', ar: 'الزومبا' },
    { word: 'Aerobics', ar: 'التمارين الهوائية' }, { word: 'Swimming', ar: 'السباحة' }, { word: 'Running', ar: 'الجري' },
    { word: 'Cycling', ar: 'ركوب الدراجات' }, { word: 'Hiking', ar: 'المشي لمسافات طويلة' }, { word: 'Team Sports', ar: 'الرياضات الجماعية' },
    { word: 'Individual Sports', ar: 'الرياضات الفردية' }, { word: 'Competitive Sports', ar: 'الرياضات التنافسية' }, { word: 'Recreational Sports', ar: 'الرياضات الترفيهية' },
    { word: 'Professional Sports', ar: 'الرياضات الاحترافية' }, { word: 'Doping', ar: 'المنشطات' }, { word: 'Fair Play', ar: 'اللعب النظيف' },
    { word: 'Sportsmanship', ar: 'الروح الرياضية' }, { word: 'Athlete', ar: 'رياضي' }, { word: 'Coach', ar: 'مدرب' },
    { word: 'Referee', ar: 'حكم' }, { word: 'Spectator', ar: 'متفرج' }, { word: 'Fan', ar: 'مشجع' },
  ];

  const startIndex = (levelNum - 1) * 15;
  const selectedTerms = terms.slice(startIndex, startIndex + 15);

  return selectedTerms.map((term, index) => {
    const incorrectOptions = shuffleArray(terms.filter(t => t.ar !== term.ar).map(t => t.ar)).slice(0, 2);
    return {
      id: `eng-s${levelNum}-q${index + 1}`,
      type: 'word-translation',
      questionText: term.word,
      options: shuffleArray([term.ar, ...incorrectOptions]),
      correct: term.ar,
    };
  });
};

// دالة مساعدة لإنشاء أسئلة مفردات فريدة لكل مستوى (الفلك)
const generateAstronomyQuestions = (levelNum: number): Question[] => {
  const terms = [
    { word: 'Earth', ar: 'الأرض' }, { word: 'Astronomy', ar: 'علم الفلك' }, { word: 'Sun', ar: 'الشمس' },
    { word: 'Solar System', ar: 'النظام الشمسي' }, { word: 'Orbit', ar: 'مدار' }, { word: 'Planet', ar: 'كوكب' },
    { word: 'Moon', ar: 'القمر' }, { word: 'Star', ar: 'نجم' }, { word: 'Galaxy', ar: 'مجرة' },
    { word: 'Universe', ar: 'الكون' }, { word: 'Telescope', ar: 'تلسكوب' }, { word: 'Astronaut', ar: 'رائد فضاء' },
    { word: 'Satellite', ar: 'قمر صناعي' }, { word: 'Rocket', ar: 'صاروخ' }, { word: 'Space Station', ar: 'محطة فضائية' },
    { word: 'Gravity', ar: 'الجاذبية' }, { word: 'Light Year', ar: 'سنة ضوئية' }, { word: 'Comet', ar: 'مذنب' },
    { word: 'Asteroid', ar: 'كويكب' }, { word: 'Meteor', ar: 'نيزك' }, { word: 'Black Hole', ar: 'ثقب أسود' },
    { word: 'Nebula', ar: 'سديم' }, { word: 'Constellation', ar: 'كوكبة' }, { word: 'Big Bang', ar: 'الانفجار العظيم' },
    { word: 'Dark Matter', ar: 'المادة المظلمة' }, { word: 'Solar Eclipse', ar: 'كسوف الشمس' }, { word: 'Lunar Eclipse', ar: 'خسوف القمر' },
    { word: 'Space Exploration', ar: 'استكشاف الفضاء' }, { word: 'Cosmic Radiation', ar: 'الإشعاع الكوني' }, { word: 'Space Shuttle', ar: 'مكوك فضائي' },
    { word: 'Mars', ar: 'المريخ' }, { word: 'Venus', ar: 'الزهرة' }, { word: 'Jupiter', ar: 'المشتري' },
    { word: 'Saturn', ar: 'زحل' }, { word: 'Mercury', ar: 'عطارد' }, { word: 'Milky Way', ar: 'درب التبانة' },
    { word: 'Astronomer', ar: 'عالم فلك' }, { word: 'Observatory', ar: 'مرصد فلكي' }, { word: 'Space Probe', ar: 'مسبار فضائي' },
    { word: 'Extraterrestrial', ar: 'كائن فضائي' }, { word: 'Cosmology', ar: 'علم الكونيات' }, { word: 'Astrophysics', ar: 'الفيزياء الفلكية' },
    { word: 'Exoplanet', ar: 'كوكب خارج المجموعة الشمسية' }, { word: 'Habitable Zone', ar: 'المنطقة الصالحة للسكن' }, { word: 'Red Giant', ar: 'نجم عملاق أحمر' },
    { word: 'White Dwarf', ar: 'قزم أبيض' }, { word: 'Supernova', ar: 'مستعر أعظم' }, { word: 'Neutron Star', ar: 'نجم نيوتروني' },
    { word: 'Pulsar', ar: 'نجم نابض' }, { word: 'Quasar', ar: 'نجم زائف' }, { word: 'Cosmic Microwave Background', ar: 'إشعاع الخلفية الكونية الميكروي' },
    { word: 'Dark Energy', ar: 'الطاقة المظلمة' }, { word: 'Multiverse', ar: 'الأكوان المتعددة' }, { word: 'Wormhole', ar: 'الثقب الدودي' },
    { word: 'Time Dilation', ar: 'تمدد الزمن' }, { word: 'Relativity', ar: 'النسبية' }, { word: 'Quantum Mechanics', ar: 'ميكانيكا الكم' },
    { word: 'String Theory', ar: 'نظرية الأوتار' }, { word: 'Gravitational Waves', ar: 'الموجات الثقالية' }, { word: 'Hubble Space Telescope', ar: 'تلسكوب هابل الفضائي' },
    { word: 'James Webb Space Telescope', ar: 'تلسكوب جيمس ويب الفضائي' }, { word: 'ISS (International Space Station)', ar: 'محطة الفضاء الدولية' }, { word: 'Space X', ar: 'سبيس إكس' },
    { word: 'NASA', ar: 'ناسا' }, { word: 'ESA (European Space Agency)', ar: 'وكالة الفضاء الأوروبية' }, { word: 'Roscosmos', ar: 'روسكوزموس' },
    { word: 'CASA (Chinese Academy of Space Technology)', ar: 'الأكاديمية الصينية لتكنولوجيا الفضاء' }, { word: 'ISRO (Indian Space Research Organisation)', ar: 'منظمة البحوث الفضائية الهندية' }, { word: 'JAXA (Japan Aerospace Exploration Agency)', ar: 'وكالة استكشاف الفضاء اليابانية' },
    { word: 'Space Tourism', ar: 'السياحة الفضائية' }, { word: 'Colonization of Mars', ar: 'استعمار المريخ' }, { word: 'Terraforming', ar: 'تكييف الكواكب' },
    { word: 'Asteroid Mining', ar: 'تعدين الكويكبات' }, { word: 'Space Debris', ar: 'الحطام الفضائي' }, { word: 'Light Pollution', ar: 'التلوث الضوئي' },
    { word: 'SETI (Search for Extraterrestrial Intelligence)', ar: 'البحث عن ذكاء خارج الأرض' }, { word: 'Dyson Sphere', ar: 'كرة دايسون' }, { word: 'Kardashev Scale', ar: 'مقياس كارداشيف' },
    { word: 'Fermi Paradox', ar: 'مفارقة فيرمي' }, { word: 'Great Filter', ar: 'المرشح العظيم' }, { word: 'Anthropic Principle', ar: 'المبدأ الأنثروبي' },
    { word: 'Cosmic Rays', ar: 'الأشعة الكونية' }, { word: 'Solar Flares', ar: 'التوهجات الشمسية' }, { word: 'Coronal Mass Ejection (CME)', ar: 'الانبعاث الكتلي الإكليلي' },
    { word: 'Aurora', ar: 'الشفق القطبي' }, { word: 'Magnetosphere', ar: 'الغلاف المغناطيسي' }, { word: 'Ionosphere', ar: 'الغلاف الأيوني' },
    { word: 'Troposphere', ar: 'التروبوسفير' }, { word: 'Stratosphere', ar: 'الستراتوسفير' }, { word: 'Mesosphere', ar: 'الميزوسفير' },
    { word: 'Thermosphere', ar: 'الثرموسفير' }, { word: 'Exosphere', ar: 'الغلاف الخارجي' }, { word: 'Atmosphere', ar: 'الغلاف الجوي' },
    { word: 'Ozone Layer', ar: 'طبقة الأوزون' }, { word: 'Greenhouse Effect', ar: 'تأثير الاحتباس الحراري' }, { word: 'Global Warming', ar: 'الاحترار العالمي' },
    { word: 'Climate Zones', ar: 'المناطق المناخية' }, { word: 'Weather Patterns', ar: 'أنماط الطقس' }, { word: 'Ocean Currents', ar: 'التيارات المحيطية' },
    { word: 'Plate Tectonics', ar: 'تكتونية الصفائح' }, { word: 'Volcanoes', ar: 'البراكين' }, { word: 'Earthquakes', ar: 'الزلازل' },
    { word: 'Tsunamis', ar: 'تسونامي' }, { word: 'Glaciers', ar: 'الأنهار الجليدية' }, { word: 'Ice Caps', ar: 'القلنسوات الجليدية' },
    { word: 'Polar Regions', ar: 'المناطق القطبية' }, { word: 'Equator', ar: 'خط الاستواء' }, { word: 'Tropics', ar: 'المدارات' },
    { word: 'Temperate Zones', ar: 'المناطق المعتدلة' }, { word: 'Arctic', ar: 'القطب الشمالي' }, { word: 'Antarctic', ar: 'القطب الجنوبي' },
    { word: 'Biosphere', ar: 'المحيط الحيوي' }, { word: 'Ecosystem', ar: 'النظام البيئي' }, { word: 'Biodiversity Hotspot', ar: 'نقطة ساخنة للتنوع البيولوجي' },
    { word: 'Endangered Species', ar: 'الأنواع المهددة بالانقراض' }, { word: 'Extinction', ar: 'الانقراض' }, { word: 'Conservation Biology', ar: 'بيولوجيا الحفظ' },
    { word: 'Ecology', ar: 'علم البيئة' }, { word: 'Geology', ar: 'علم الجيولوجيا' }, { word: 'Oceanography', ar: 'علم المحيطات' },
    { word: 'Meteorology', ar: 'علم الأرصاد الجوية' }, { word: 'Climatology', ar: 'علم المناخ' }, { word: 'Paleontology', ar: 'علم الحفريات' },
    { word: 'Anthropology', ar: 'علم الأنثروبولوجيا' }, { word: 'Archaeology', ar: 'علم الآثار' }, { word: 'History of Science', ar: 'تاريخ العلوم' },
    { word: 'Philosophy of Science', ar: 'فلسفة العلوم' }, { word: 'Scientific Method', ar: 'المنهج العلمي' }, { word: 'Hypothesis', ar: 'فرضية' },
    { word: 'Theory', ar: 'نظرية' }, { word: 'Law', ar: 'قانون علمي' }, { word: 'Experiment', ar: 'تجربة' },
    { word: 'Observation', ar: 'ملاحظة' }, { word: 'Data Analysis', ar: 'تحليل البيانات' }, { word: 'Peer Review', ar: 'مراجعة الأقران' },
    { word: 'Scientific Community', ar: 'المجتمع العلمي' }, { word: 'Nobel Prize', ar: 'جائزة نوبل' }, { word: 'Scientific Revolution', ar: 'الثورة العلمية' },
    { word: 'Enlightenment', ar: 'عصر التنوير' }, { word: 'Renaissance', ar: 'عصر النهضة' }, { word: 'Industrial Revolution', ar: 'الثورة الصناعية' },
    { word: 'Information Age', ar: 'عصر المعلومات' }, { word: 'Digital Revolution', ar: 'الثورة الرقمية' }, { word: 'Artificial Intelligence', ar: 'الذكاء الاصطناعي' },
    { word: 'Machine Learning', ar: 'التعلم الآلي' }, { word: 'Deep Learning', ar: 'التعلم العميق' }, { word: 'Robotics', ar: 'الروبوتات' },
    { word: 'Biotechnology', ar: 'التكنولوجيا الحيوية' }, { word: 'Nanotechnology', ar: 'تكنولوجيا النانو' }, { word: 'Quantum Computing', ar: 'الحوسبة الكمومية' },
    { word: 'Virtual Reality', ar: 'الواقع الافتراضي' }, { word: 'Augmented Reality', ar: 'الواقع المعزز' }, { word: 'Cybernetics', ar: 'السيبرنيطيقا' },
  ];

  const startIndex = (levelNum - 1) * 15;
  const selectedTerms = terms.slice(startIndex, startIndex + 15);

  return selectedTerms.map((term, index) => {
    const incorrectOptions = shuffleArray(terms.filter(t => t.ar !== term.ar).map(t => t.ar)).slice(0, 2);
    return {
      id: `eng-a${levelNum}-q${index + 1}`,
      type: 'word-translation',
      questionText: term.word,
      options: shuffleArray([term.ar, ...incorrectOptions]),
      correct: term.ar,
    };
  });
};


export const englishQuizData = {
  sections: {
    'grammar': {
      levels: Array.from({ length: 10 }, (_, i) => `level${i + 1}`).reduce((acc, levelName, idx) => {
        acc[levelName] = generateGrammarQuestions(idx + 1);
        return acc;
      }, {} as Record<string, Question[]>),
    },
    'ethics': {
      levels: Array.from({ length: 10 }, (_, i) => `level${i + 1}`).reduce((acc, levelName, idx) => {
        acc[levelName] = generateEthicsQuestions(idx + 1);
        return acc;
      }, {} as Record<string, Question[]>),
    },
    'safety': {
      levels: Array.from({ length: 10 }, (_, i) => `level${i + 1}`).reduce((acc, levelName, idx) => {
        acc[levelName] = generateSafetyQuestions(idx + 1);
        return acc;
      }, {} as Record<string, Question[]>),
    },
    'astronomy': {
      levels: Array.from({ length: 10 }, (_, i) => `level${i + 1}`).reduce((acc, levelName, idx) => {
        acc[levelName] = generateAstronomyQuestions(idx + 1);
        return acc;
      }, {} as Record<string, Question[]>),
    },
  },
};
