// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eujerhawasdpjjejwyyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1amVyaGF3YXNkcGpqZWp3eXlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NzgzMTAsImV4cCI6MjA2ODI1NDMxMH0.24dlhKhl0adDlQteCMvOsSKNriilQICu580IrCp7ySQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});