// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hegypxotdbopdflopypa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlZ3lweG90ZGJvcGRmbG9weXBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMzQxOTIsImV4cCI6MjA3MTgxMDE5Mn0.FY95g5L6OCuioh3dm5VQghTYiTuLWegssZVOd1tt44w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
